# SPDX-FileCopyrightText: Jakob Naucke <jnaucke@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "confidential-cluster-operator-test-lib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
k8s-openapi.workspace = true
kube.workspace = true
serde.workspace = true
serde_json.workspace = true
